server:
 port: 8080
 
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
   gateway:
       routes:
        - id: USER-SERVICE
          uri:
            lb://USER-SERVICE
          predicates:
            - Path=/auth/**, /users/**, /api/user/**, /
        
        - id: TASK-SERVICE
          uri:
            lb://TASK-SERVICE
          predicates:
            - Path=/api/tasks/**, /tasks/**
        
        - id: SUBMISSION-SERVICE
          uri:
            lb://SUBMISSION-SERVICE
          predicates:
            - Path=/api/submission/**, /submission/**
       default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
       globalcors:
         cors-configurations:
           '[/**]':
             allowedOrigins: "*"
             allowedMethods: "*"
             allowedHeaders: "*"
             
    
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/